// This file is generated by Slice Machine. Update with care!

import IntroTextImage from './IntroTextImage';

export {
	IntroTextImage,
};

export const components = {
	intro_text_image: IntroTextImage,
};
